name: Check

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    avoid_redundancy:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
            - name: Install Dependencies
              run: npm ci
            - name: Cache node_modules
              uses: actions/upload-artifact@v2
              with:
                  name: node_modules
                  path: node_modules

    lint:
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
            - name: Download node_modules
              uses: actions/download-artifact@v2
              with:
                  name: node_modules
                  path: node_modules
            - name: Lint
              run: npm run lint
    build:
        needs: [install, lint]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
            - name: Download node_modules
              uses: actions/download-artifact@v2
              with:
                  name: node_modules
                  path: node_modules
            - name: Build
              run: npm run build
            - name: Cache library
              uses: actions/upload-artifact@v2
              with:
                  name: lib
                  path: lib
    test:
        needs: [build, lint, install]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
            - name: Download node_modules
              uses: actions/download-artifact@v2
              with:
                  name: node_modules
                  path: node_modules
            - name: Download library
              uses: actions/download-artifact@v2
              with:
                  name: lib
                  path: lib
            - name: Test
              run: DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} npm run test
