name: Publish to NPM
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
            - name: Intall dependencies
              run: npm ci
            - name: Build library
              run: npm run build
            - name: Cache library
              uses: actions/upload-artifact@v2
              with:
                  name: lib
                  path: lib
    publish:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.10.0
                  registry-url: 'https://registry.npmjs.org'
            - name: Download library
              uses: actions/download-artifact@v2
              with:
                  name: lib
                  path: lib
            - name: Publish package on NPM 📦
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
